<span style = "color:red">**Lecture 2 - 12.04.24**</span>

In [1]:
print("Hello World")

Hello World


In [2]:
x=10
x

10

In [3]:
"ab" + " cd"

'ab cd'

In [4]:
type(x)

int

In [5]:
x=[1,2,3,4,'a','b']
type(x)

list

**tuple**

In [6]:
x2=(1,2,3,4,'a','b')
type(x2)

tuple

**Set**

In [7]:
set = {1,2,3,4,'a',"b",'b',4,6}

In [8]:
set

{1, 2, 3, 4, 6, 'a', 'b'}

**Dict**

In [9]:
d ={'Fruit':'apple','Vegetable':'cucumber'}

In [10]:
type(d)

dict

In [11]:
d

{'Fruit': 'apple', 'Vegetable': 'cucumber'}

## **Operators**

In [12]:
7//2 #floor division

3

In [13]:
7%2 #remnant of division

1

In [14]:
2**3 #power

8

In [15]:
pow(3,3) #power functin

27

In [16]:
6==6

True

In [17]:
x = [1,2,3,4,5,6]

In [18]:
y = [3,4,7,8,9,90]

In [19]:
x and y

[3, 4, 7, 8, 9, 90]

## Assignment

In [20]:
m = 3
n = 5

In [21]:
m = m+10
print(m)

13


In [22]:
n += 3 # same as n = n + 3
print(n)

8


In [23]:
n = n + 3
n

11

# Membership

In [24]:
s = "Python is good programming"

In [25]:
'y' in s

True

In [26]:
'w' in s

False

[Note] Deep note here

<span style = "color:blue">Deep note in blue</span>

## String operations

In [27]:
S = 'Hello World'

In [28]:
S + '!'

'Hello World!'

In [29]:
len(S)

11

In [30]:
S.upper()

'HELLO WORLD'

In [31]:
S.lower()

'hello world'

In [32]:
S.capitalize()

'Hello world'

In [33]:
S.casefold()

'hello world'

In [34]:
S2 = 'Bye World'

In [35]:
#S.join()

# Methods for Text Data Analysis

In [36]:
x = "Inflation increased in the past 10 years"
x

'Inflation increased in the past 10 years'

In [37]:
x.find("Inflation")

0

In [38]:
x.find('D')

-1

In [39]:
x.find('d')

18

In [40]:
x.split()[2].capitalize()


'In'

[NOTE] **Because in for loop operation we dont want to change the values, thus immutublility can be important so tuple is good in this case**

# other operation

In [41]:
x = [1,2,3,4,5,3]
x

[1, 2, 3, 4, 5, 3]

In [42]:
x.extend([3,4,5])
x

[1, 2, 3, 4, 5, 3, 3, 4, 5]

In [43]:
x.sort()
x

[1, 2, 3, 3, 3, 4, 4, 5, 5]

In [44]:
x.pop()
x

[1, 2, 3, 3, 3, 4, 4, 5]

## Conditionals / If-else

In [45]:
x = -5
if x>0:
    print("Positive")
elif x == 0:
    print("Zero")
else:
    print("Negative")


Negative


# Loops

x = 0 

while x<5:
    x += 1
    print(x)

In [46]:
xs = [1,2,3,4,5,6,7,8]

In [47]:
for x in xs:
    if x < 2:
        print(x**2)
    elif x== 2:
        print(x+2)
    else:
        print(x**3)

1
4
27
64
125
216
343
512


[Note] def(x,y) x,y called parameters if you assign value when you call the function

In [48]:
def greater_function(x,y):
    if x>y:
        return x
    else:
        return y
t = greater_function(3,4)
t

4

# Indexing

In [49]:
list1 = [4,2,7.5,3]

In [50]:
list2 = [[4,5,6], "Python", 'Java', (2,3,4)]

In [51]:
lists = [list1, list2]
for i in lists:
    print(i[0])

4
[4, 5, 6]


In [52]:
list2[0][0]

4

In [53]:
for i in lists:
    print(i[0:1][0])

4
[4, 5, 6]


In [54]:
sub_list = list2[:3]

In [55]:
sub_list[0][1] = 'RStudio'
sub_list

[[4, 'RStudio', 6], 'Python', 'Java']

In [56]:
s = "This is a string!"

In [57]:
s

'This is a string!'

In [58]:
type(s)

str

In [59]:
print(s.upper())

THIS IS A STRING!


# Classes in Python

In [60]:
class Cat(object):

    def __init__(self, name, age):
        self.name = name
        self.age = age 

    def bark(self):
        return "Miau!"

    def compute_ageinmonths(self):
        return 12*self.age

    def __str__(self):
        var = str(self.age)
        return "Cat " + self.name + " is" + " " + var + " years old! Mmmm!"

In [61]:
cat1 = Cat("Claus", 20)

print(cat1.name, cat1.age)

Claus 20


In [62]:
cat1.bark()

'Miau!'

In [63]:
cat1.compute_ageinmonths()

240

In [64]:
cat1.__str__()

'Cat Claus is 20 years old! Mmmm!'

# Speech data

In [66]:
import pandas as pd
import numpy as np

In [73]:
import csv

with open('all_ECB_speeches.csv', encoding = 'utf-8') as csvfile:
    read_in_new1 = csv.reader(csvfile, delimiter='|')
    for row in read_in_new1:
            print(row)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [82]:
import csv 
L = [8]

with open('all_ECB_speeches.csv', encoding = 'utf-8') as csvfile:
    read_in_new = csv.reader(csvfile, delimiter='|')
    for i, line in enumerate(read_in_new):
        if i in L:
            print(line)
            x = line 
            break

['2024-03-14', 'Isabel Schnabel', 'The Eurosystem’s operational framework', 'Speech by Isabel Schnabel, Member of the Executive Board of the ECB, at the Money Market Contact Group meeting', "  SPEECH  The Eurosystem’s operational framework   Speech by Isabel Schnabel, Member of the Executive Board of the ECB, at the Money Market Contact Group meeting Frankfurt am Main, 14 March 2024 Since 2015, the Eurosystem has been operating under a de facto supply-driven floor system. This was the result of the monetary policy actions taken in the run-up to and during the pandemic to preserve price stability in the euro area.  Faced with years of persistently low inflation and the greatest economic contraction on record in 2020, we conducted large-scale asset purchases and targeted longer-term refinancing operations (TLTROs), thereby injecting a significant amount of central bank reserves into the financial system. The resulting easing of financing conditions supported economic activity in the purs

In [83]:
x

['2024-03-14',
 'Isabel Schnabel',
 'The Eurosystem’s operational framework',
 'Speech by Isabel Schnabel, Member of the Executive Board of the ECB, at the Money Market Contact Group meeting',
 "  SPEECH  The Eurosystem’s operational framework   Speech by Isabel Schnabel, Member of the Executive Board of the ECB, at the Money Market Contact Group meeting Frankfurt am Main, 14 March 2024 Since 2015, the Eurosystem has been operating under a de facto supply-driven floor system. This was the result of the monetary policy actions taken in the run-up to and during the pandemic to preserve price stability in the euro area.  Faced with years of persistently low inflation and the greatest economic contraction on record in 2020, we conducted large-scale asset purchases and targeted longer-term refinancing operations (TLTROs), thereby injecting a significant amount of central bank reserves into the financial system. The resulting easing of financing conditions supported economic activity in the 

In [84]:
corpus = x[4]

In [85]:
corpus[:500]

'  SPEECH  The Eurosystem’s operational framework   Speech by Isabel Schnabel, Member of the Executive Board of the ECB, at the Money Market Contact Group meeting Frankfurt am Main, 14 March 2024 Since 2015, the Eurosystem has been operating under a de facto supply-driven floor system. This was the result of the monetary policy actions taken in the run-up to and during the pandemic to preserve price stability in the euro area.  Faced with years of persistently low inflation and the greatest econo'

In [86]:
type(corpus)

str

In [87]:
len(corpus)

32342

In [90]:
corpus1=corpus.lstrip(corpus[2:157])

In [91]:
corpus1

"g Frankfurt am Main, 14 March 2024 Since 2015, the Eurosystem has been operating under a de facto supply-driven floor system. This was the result of the monetary policy actions taken in the run-up to and during the pandemic to preserve price stability in the euro area.  Faced with years of persistently low inflation and the greatest economic contraction on record in 2020, we conducted large-scale asset purchases and targeted longer-term refinancing operations (TLTROs), thereby injecting a significant amount of central bank reserves into the financial system. The resulting easing of financing conditions supported economic activity in the pursuit of our mandate. As reserves were well in excess of banks’ liquidity needs, short-term money market rates have been trading in the vicinity of the rate at which the Eurosystem remunerates overnight deposits – the deposit facility rate, or DFR. More recently, the volume of reserves has started to visibly decline because of the sharp reversal in t

In [92]:
corpus1[:500]

'g Frankfurt am Main, 14 March 2024 Since 2015, the Eurosystem has been operating under a de facto supply-driven floor system. This was the result of the monetary policy actions taken in the run-up to and during the pandemic to preserve price stability in the euro area.  Faced with years of persistently low inflation and the greatest economic contraction on record in 2020, we conducted large-scale asset purchases and targeted longer-term refinancing operations (TLTROs), thereby injecting a signif'

In [93]:
corpus2=corpus1.rstrip(corpus1[18040:])

In [94]:
corpus2[17000:]

''

In [95]:
corpus3=corpus2.rstrip(corpus2[17969:])

In [96]:
corpus3[17000:]

''

In [97]:
corpus4=corpus3.lstrip(corpus3[:3])

In [98]:
corpus4[:500]

'rankfurt am Main, 14 March 2024 Since 2015, the Eurosystem has been operating under a de facto supply-driven floor system. This was the result of the monetary policy actions taken in the run-up to and during the pandemic to preserve price stability in the euro area.  Faced with years of persistently low inflation and the greatest economic contraction on record in 2020, we conducted large-scale asset purchases and targeted longer-term refinancing operations (TLTROs), thereby injecting a significa'

In [99]:
corpus5=corpus4.rstrip(corpus4[17957:])

In [100]:
corpus5[17000:]

''

# <span style ="color:red">NumPy, Pandas, Scikit-learn</span>

##### Importing Statements

In [103]:
import pandas as pd
import numpy as np

In [105]:
v = np.array([7,8,9,10])
v

array([ 7,  8,  9, 10])

In [107]:
l = [7,8,9,10]
l

[7, 8, 9, 10]

In [109]:
type(v) == type(l)

False

In [112]:
v[::-1]

array([10,  9,  8,  7])

In [113]:
v + 1

array([ 8,  9, 10, 11])

In [115]:
v**2

array([ 49,  64,  81, 100])