<span style = "color:red">**Lecture 2 - 12.04.24**</span>

In [96]:
print("Hello World")

Hello World


In [97]:
x=10
x

10

In [98]:
"ab" + " cd"

'ab cd'

In [99]:
type(x)

int

In [100]:
x=[1,2,3,4,'a','b']
type(x)

list

**tuple**

In [101]:
x2=(1,2,3,4,'a','b')
type(x2)

tuple

**Set**

In [102]:
set = {1,2,3,4,'a',"b",'b',4,6}

In [103]:
set

{1, 2, 3, 4, 6, 'a', 'b'}

**Dict**

In [104]:
d ={'Fruit':'apple','Vegetable':'cucumber'}

In [105]:
type(d)

dict

In [106]:
d

{'Fruit': 'apple', 'Vegetable': 'cucumber'}

## **Operators**

In [107]:
7//2 #floor division

3

In [108]:
7%2 #remnant of division

1

In [109]:
2**3 #power

8

In [110]:
pow(3,3) #power functin

27

In [111]:
6==6

True

In [112]:
x = [1,2,3,4,5,6]

In [113]:
y = [3,4,7,8,9,90]

In [114]:
x and y

[3, 4, 7, 8, 9, 90]

## Assignment

In [115]:
m = 3
n = 5

In [116]:
m = m+10
print(m)

13


In [117]:
n += 3 # same as n = n + 3
print(n)

8


In [118]:
n = n + 3
n

11

# Membership

In [119]:
s = "Python is good programming"

In [120]:
'y' in s

True

In [121]:
'w' in s

False

[Note] Deep note here

<span style = "color:blue">Deep note in blue</span>

## String operations

In [122]:
S = 'Hello World'

In [123]:
S + '!'

'Hello World!'

In [124]:
len(S)

11

In [125]:
S.upper()

'HELLO WORLD'

In [126]:
S.lower()

'hello world'

In [127]:
S.capitalize()

'Hello world'

In [128]:
S.casefold()

'hello world'

In [129]:
S2 = 'Bye World'

In [130]:
#S.join()

# Methods for Text Data Analysis

In [131]:
x = "Inflation increased in the past 10 years"
x

'Inflation increased in the past 10 years'

In [132]:
x.find("Inflation")

0

In [133]:
x.find('D')

-1

In [134]:
x.find('d')

18

In [135]:
x.split()[2].capitalize()


'In'

[NOTE] **Because in for loop operation we dont want to change the values, thus immutublility can be important so tuple is good in this case**

# other operation

In [136]:
x = [1,2,3,4,5,3]
x

[1, 2, 3, 4, 5, 3]

In [137]:
x.extend([3,4,5])
x

[1, 2, 3, 4, 5, 3, 3, 4, 5]

In [138]:
x.sort()
x

[1, 2, 3, 3, 3, 4, 4, 5, 5]

In [139]:
x.pop()
x

[1, 2, 3, 3, 3, 4, 4, 5]

## Conditionals / If-else

In [140]:
x = -5
if x>0:
    print("Positive")
elif x == 0:
    print("Zero")
else:
    print("Negative")


Negative


# Loops

x = 0 

while x<5:
    x += 1
    print(x)

In [141]:
xs = [1,2,3,4,5,6,7,8]

In [142]:
for x in xs:
    if x < 2:
        print(x**2)
    elif x== 2:
        print(x+2)
    else:
        print(x**3)

1
4
27
64
125
216
343
512


[Note] def(x,y) x,y called parameters if you assign value when you call the function

In [143]:
def greater_function(x,y):
    if x>y:
        return x
    else:
        return y
t = greater_function(3,4)
t

4

# Indexing

In [144]:
list1 = [4,2,7.5,3]

In [145]:
list2 = [[4,5,6], "Python", 'Java', (2,3,4)]

In [146]:
lists = [list1, list2]
for i in lists:
    print(i[0])

4
[4, 5, 6]


In [147]:
list2[0][0]

4

In [148]:
for i in lists:
    print(i[0:1][0])

4
[4, 5, 6]


In [149]:
sub_list = list2[:3]

In [150]:
sub_list[0][1] = 'RStudio'
sub_list

[[4, 'RStudio', 6], 'Python', 'Java']

In [151]:
s = "This is a string!"

In [152]:
s

'This is a string!'

In [153]:
type(s)

str

In [154]:
print(s.upper())

THIS IS A STRING!


# Classes in Python

In [155]:
class Cat(object):

    def __init__(self, name, age):
        self.name = name
        self.age = age 

    def bark(self):
        return "Miau!"

    def compute_ageinmonths(self):
        return 12*self.age

    def __str__(self):
        var = str(self.age)
        return "Cat " + self.name + " is" + " " + var + " years old! Mmmm!"

In [156]:
cat1 = Cat("Claus", 20)

print(cat1.name, cat1.age)

Claus 20


In [157]:
cat1.bark()

'Miau!'

In [158]:
cat1.compute_ageinmonths()

240

In [159]:
cat1.__str__()

'Cat Claus is 20 years old! Mmmm!'

# Speech data

In [160]:
import pandas as pd
import numpy as np

In [161]:
import csv

with open('all_ECB_speeches.csv', encoding = 'utf-8') as csvfile:
    read_in_new1 = csv.reader(csvfile, delimiter='|')
    for row in read_in_new1:
            print(row)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



['2018-02-23', 'Benoît Cœuré', 'The persistence and signalling power of central bank asset purchase programmes', 'Speech by Benoît Cœuré, Member of the Executive Board of the ECB, at the 2018 US Monetary Policy Forum, New York City, 23 February 2018', '  The persistence and signalling power of central bank asset purchase programmes   Speech by Benoît Cœuré, Member of the Executive Board of the ECB, at the 2018 US Monetary Policy Forum, New York City, 23 February 2018 The financial crisis has seen central banks launch asset purchase programmes of unprecedented scope and scale, so as to provide additional policy stimulus as interest rates approached the lower bound. This period has yielded many insights into how these programmes work and their various channels of transmission.[1] But one question that has remained open is the relative importance of their “stock” and “flow” effects. The issue is not so much about which of the two effects dominates. The literature is fairly clear on this: 

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



['2016-10-03', 'Yves Mersch', 'The challenge of low interest rates for banks within the banking union', 'Speech by Yves Mersch, Member of the Executive Board of the ECB, Public Roundtable at the University of Luxembourg on “Banking Union – Quo Vadis?”, Luxembourg, 3 October 2016', "  The challenge of low interest rates for banks within the banking union   Speech by Yves Mersch, Member of the Executive Board of the ECB, Public Roundtable at the University of Luxembourg on “Banking Union – Quo Vadis?”, Luxembourg, 3 October 2016 We are sitting here tonight in a room that was named after the first president of the University of Luxembourg, the late Professor François Tavenas. He once said “change is mandatory, survival is optional; choose wisely”[1].  Even though Tavenas was speaking about the impact of globalisation on universities, what he said also holds true for the euro area and its recent history.  When the financial crisis struck, it was clear that things could not go on as they ha

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



['2008-09-05', 'Jean-Claude Trichet', 'Risk and the Macro-economy', 'Keynote address by Jean-Claude Trichet, President of the ECB at the conference ‘The ECB and its Watchers X’Frankfurt am Main, 5 September 2008', '  Risk and the Macro-economy   Keynote address by Jean-Claude Trichet, President of the ECB at the conference ‘The ECB and its Watchers X’Frankfurt am Main, 5 September 2008 Ladies and gentlemen, After an extended period of ample financial market liquidity and exceptionally low rewards for risk, the loss in the value of important classes of real assets has imparted a sharp deterioration in investor appetite. Rises in commodity prices, by eroding consumers’ purchasing power and real income prospects, have reinforced households’ risk aversion.  A long phase of heightened risk tolerance in our economies has come to an end. To the extent that the more recent turns in the markets correct past excesses, this is a welcome – if painful – process that we had anticipated and asked mar

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [162]:
import csv 
L = [8]

with open('all_ECB_speeches.csv', encoding = 'utf-8') as csvfile:
    read_in_new = csv.reader(csvfile, delimiter='|')
    for i, line in enumerate(read_in_new):
        if i in L:
            print(line)
            x = line 
            break

['2024-03-14', 'Isabel Schnabel', 'The Eurosystem’s operational framework', 'Speech by Isabel Schnabel, Member of the Executive Board of the ECB, at the Money Market Contact Group meeting', "  SPEECH  The Eurosystem’s operational framework   Speech by Isabel Schnabel, Member of the Executive Board of the ECB, at the Money Market Contact Group meeting Frankfurt am Main, 14 March 2024 Since 2015, the Eurosystem has been operating under a de facto supply-driven floor system. This was the result of the monetary policy actions taken in the run-up to and during the pandemic to preserve price stability in the euro area.  Faced with years of persistently low inflation and the greatest economic contraction on record in 2020, we conducted large-scale asset purchases and targeted longer-term refinancing operations (TLTROs), thereby injecting a significant amount of central bank reserves into the financial system. The resulting easing of financing conditions supported economic activity in the purs

In [163]:
x

['2024-03-14',
 'Isabel Schnabel',
 'The Eurosystem’s operational framework',
 'Speech by Isabel Schnabel, Member of the Executive Board of the ECB, at the Money Market Contact Group meeting',
 "  SPEECH  The Eurosystem’s operational framework   Speech by Isabel Schnabel, Member of the Executive Board of the ECB, at the Money Market Contact Group meeting Frankfurt am Main, 14 March 2024 Since 2015, the Eurosystem has been operating under a de facto supply-driven floor system. This was the result of the monetary policy actions taken in the run-up to and during the pandemic to preserve price stability in the euro area.  Faced with years of persistently low inflation and the greatest economic contraction on record in 2020, we conducted large-scale asset purchases and targeted longer-term refinancing operations (TLTROs), thereby injecting a significant amount of central bank reserves into the financial system. The resulting easing of financing conditions supported economic activity in the 

In [164]:
corpus = x[4]

In [165]:
corpus[:500]

'  SPEECH  The Eurosystem’s operational framework   Speech by Isabel Schnabel, Member of the Executive Board of the ECB, at the Money Market Contact Group meeting Frankfurt am Main, 14 March 2024 Since 2015, the Eurosystem has been operating under a de facto supply-driven floor system. This was the result of the monetary policy actions taken in the run-up to and during the pandemic to preserve price stability in the euro area.  Faced with years of persistently low inflation and the greatest econo'

In [166]:
type(corpus)

str

In [167]:
len(corpus)

32342

In [168]:
corpus1=corpus.lstrip(corpus[2:157])

In [169]:
corpus1

"g Frankfurt am Main, 14 March 2024 Since 2015, the Eurosystem has been operating under a de facto supply-driven floor system. This was the result of the monetary policy actions taken in the run-up to and during the pandemic to preserve price stability in the euro area.  Faced with years of persistently low inflation and the greatest economic contraction on record in 2020, we conducted large-scale asset purchases and targeted longer-term refinancing operations (TLTROs), thereby injecting a significant amount of central bank reserves into the financial system. The resulting easing of financing conditions supported economic activity in the pursuit of our mandate. As reserves were well in excess of banks’ liquidity needs, short-term money market rates have been trading in the vicinity of the rate at which the Eurosystem remunerates overnight deposits – the deposit facility rate, or DFR. More recently, the volume of reserves has started to visibly decline because of the sharp reversal in t

In [170]:
corpus1[:500]

'g Frankfurt am Main, 14 March 2024 Since 2015, the Eurosystem has been operating under a de facto supply-driven floor system. This was the result of the monetary policy actions taken in the run-up to and during the pandemic to preserve price stability in the euro area.  Faced with years of persistently low inflation and the greatest economic contraction on record in 2020, we conducted large-scale asset purchases and targeted longer-term refinancing operations (TLTROs), thereby injecting a signif'

In [171]:
corpus2=corpus1.rstrip(corpus1[18040:])

In [172]:
corpus2[17000:]

''

In [173]:
corpus3=corpus2.rstrip(corpus2[17969:])

In [174]:
corpus3[17000:]

''

In [175]:
corpus4=corpus3.lstrip(corpus3[:3])

In [176]:
corpus4[:500]

'rankfurt am Main, 14 March 2024 Since 2015, the Eurosystem has been operating under a de facto supply-driven floor system. This was the result of the monetary policy actions taken in the run-up to and during the pandemic to preserve price stability in the euro area.  Faced with years of persistently low inflation and the greatest economic contraction on record in 2020, we conducted large-scale asset purchases and targeted longer-term refinancing operations (TLTROs), thereby injecting a significa'

In [177]:
corpus5=corpus4.rstrip(corpus4[17957:])

In [178]:
corpus5[17000:]

''

# <span style ="color:red">NumPy, Pandas, Scikit-learn</span>

##### Importing Statements

In [179]:
import pandas as pd
import numpy as np

In [180]:
v = np.array([7,8,9,10])
v

array([ 7,  8,  9, 10])

In [181]:
l = [7,8,9,10]
l

[7, 8, 9, 10]

In [182]:
type(v) == type(l)

False

In [183]:
v[::-1]

array([10,  9,  8,  7])

In [184]:
v + 1

array([ 8,  9, 10, 11])

In [185]:
v**2

array([ 49,  64,  81, 100])

# Beer Data

In [186]:
beer_data = pd.read_csv("Beer.csv")

In [187]:
beer_data.head()

place   pop2023  growthRate    area         country cca3 cca2  ccn3  \
0    203  10495295     0.00013   78865  Czech Republic  CZE   CZ   203   
1     40   8958960     0.00216   83871         Austria  AUT   AT    40   
2    616  41026067     0.02933  312679          Poland  POL   PL   616   
3    642  19892812     0.01188  238391         Romania  ROU   RO   642   
4    276  83294633    -0.00090  357114         Germany  DEU   DE   276   

   region       subregion  landAreaKm   density  densityMi  Rank  consmPerCap  \
0  Europe  Eastern Europe     77198.5  135.9521   352.1158    89        181.7   
1  Europe  Western Europe     82520.0  108.5671   281.1889   100         96.8   
2  Europe  Eastern Europe    306130.0  134.0152   347.0993    37         96.0   
3  Europe  Eastern Europe    230080.0   86.4604   223.9325    64         95.0   
4  Europe  Western Europe    349390.0  238.4002   617.4564    19         92.5   

   consm  consmGals   pop2020  rank  
0   1946     514079  10708981     1  
1    872     230358   9006398     2  
2   3633     959737  37846611     3  
3   1828     482907  19237691     4  
4   7746    2046277  83783942     5

In [188]:
beer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   place        47 non-null     int64  
 1   pop2023      47 non-null     int64  
 2   growthRate   47 non-null     float64
 3   area         47 non-null     int64  
 4   country      47 non-null     object 
 5   cca3         47 non-null     object 
 6   cca2         46 non-null     object 
 7   ccn3         47 non-null     int64  
 8   region       47 non-null     object 
 9   subregion    47 non-null     object 
 10  landAreaKm   47 non-null     float64
 11  density      47 non-null     float64
 12  densityMi    47 non-null     float64
 13  Rank         47 non-null     int64  
 14  consmPerCap  47 non-null     float64
 15  consm        47 non-null     int64  
 16  consmGals    47 non-null     int64  
 17  pop2020      47 non-null     int64  
 18  rank         47 non-null     int64  
dtypes: float64

In [189]:
beer_data.shape

(47, 19)

In [190]:
beer_data.describe()

place       pop2023  growthRate          area        ccn3  \
count   47.000000  4.700000e+01   47.000000  4.700000e+01   47.000000   
mean   419.340426  1.049965e+08    0.003528  1.723488e+06  419.340426   
std    256.722933  2.888711e+08    0.014613  3.595617e+06  256.722933   
min     32.000000  1.322765e+06   -0.074480  8.870000e+03   32.000000   
25%    197.000000  5.670337e+06   -0.000380  7.284500e+04  197.000000   
50%    392.000000  1.989281e+07    0.004070  3.126790e+05  392.000000   
75%    642.500000  6.624669e+07    0.008380  7.145575e+05  642.500000   
max    840.000000  1.428628e+09    0.029330  1.709824e+07  840.000000   

         landAreaKm     density    densityMi        Rank  consmPerCap  \
count  4.700000e+01   47.000000    47.000000   47.000000    47.000000   
mean   1.657642e+06  139.341100   360.893443   69.702128    63.065957   
std    3.448114e+06  145.481066   376.795964   51.711539    28.396841   
min    8.870000e+03    3.163100     8.192500    1.000000     1.200000   
25%    7.153500e+04   34.055250    88.203000   22.000000    47.350000   
50%    2.981700e+05   86.460400   223.932500   64.000000    63.700000   
75%    7.013450e+05  175.173800   453.700250  117.000000    79.400000   
max    1.637687e+07  530.574400  1374.187600  156.000000   181.700000   

              consm     consmGals       pop2020       rank  
count     47.000000  4.700000e+01  4.700000e+01  47.000000  
mean    3294.744681  8.703795e+05  1.037694e+08  24.000000  
std     6440.503702  1.701401e+06  2.853096e+08  13.711309  
min      112.000000  2.958700e+04  1.326535e+06   1.000000  
25%      414.000000  1.093675e+05  5.488864e+06  12.500000  
50%     1680.000000  4.438090e+05  1.923769e+07  24.000000  
75%     2765.000000  7.304355e+05  6.657976e+07  35.500000  
max    36088.000000  9.533441e+06  1.439324e+09  47.000000

In [191]:
beer_data.isna().sum()

place          0
pop2023        0
growthRate     0
area           0
country        0
cca3           0
cca2           1
ccn3           0
region         0
subregion      0
landAreaKm     0
density        0
densityMi      0
Rank           0
consmPerCap    0
consm          0
consmGals      0
pop2020        0
rank           0
dtype: int64

In [198]:
beer_data.duplicated().value_counts()

False    47
Name: count, dtype: int64