# Numpy

> NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

https://numpy.org/doc/stable/index.html

Basics:

https://numpy.org/doc/stable/user/absolute_beginners.html

Installation:


In [3]:
import numpy as np

##### Vectors: One-dimensional Arrays

Create a vector `v` that contains the numbers `7, 8, 9, 10`. Use the `np.array` function ([Link to numpy documentation](https://numpy.org/doc/stable/reference/generated/numpy.array.html)).

In [4]:
v = np.array([7, 8, 9, 10])

In [5]:
type(v)

numpy.ndarray

In [6]:
v

array([ 7,  8,  9, 10])

In [7]:
print(v)

[ 7  8  9 10]


NumPy vectors might look like lists, at first sight, but they are a different data type 

In [8]:
z = [7, 8, 9, 10]

In [9]:
z

[7, 8, 9, 10]

In [11]:
type(v) == type(z)

False

Indexing and Slicing is quite similar

In [12]:
v[1:3]

array([8, 9])

In [13]:
len(v)

4

In [15]:
z[1:3]

[8, 9]

In [16]:
len(z)

4

Create a vector `v` that contains the values 14 to 47 with the help of the function `np.arange` ([Link to numpy documentation](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)).

In [17]:
v = np.arange(14, 48)

In [18]:
v

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
       31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

What is the data type of v?

In [19]:
v.dtype

dtype('int32')

What is the dimension of vector v?

In [20]:
v.ndim

1

In [21]:
v.shape

(34,)

Replace the 9. value with the number 12 

In [22]:
v[8] = 12
v

array([14, 15, 16, 17, 18, 19, 20, 21, 12, 23, 24, 25, 26, 27, 28, 29, 30,
       31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

Reverse the array (via *slicing*), to get `[47,46,....,14]` .

In [23]:
v[::-1]

array([47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31,
       30, 29, 28, 27, 26, 25, 24, 23, 12, 21, 20, 19, 18, 17, 16, 15, 14])

In [24]:
v

array([14, 15, 16, 17, 18, 19, 20, 21, 12, 23, 24, 25, 26, 27, 28, 29, 30,
       31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [25]:
v[:-1]

array([14, 15, 16, 17, 18, 19, 20, 21, 12, 23, 24, 25, 26, 27, 28, 29, 30,
       31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46])



NumPy Arrays handle operators differently that what it was for lists.

Instead of applying the operator on the whole list, the operations are done on each element of the vector.


In [26]:
v + 1

array([15, 16, 17, 18, 19, 20, 21, 22, 13, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [27]:
v * 2

array([28, 30, 32, 34, 36, 38, 40, 42, 24, 46, 48, 50, 52, 54, 56, 58, 60,
       62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94])

In [28]:
v[:3] * 3




array([42, 45, 48])

In [29]:
z * 2


[7, 8, 9, 10, 7, 8, 9, 10]

##### Matrices: Two-dimensional Arrays

Create a NumPy Array x with the help of the `np.array` function: 

```
[[1,  7, 13],
 [2,  8, 14],
 [3,  9, 15],
 [4,  10, 16],
 [5, 11, 17], 
 [6, 12, 18]]
```

In [30]:
x = np.array(
    [[1,  7, 13],
     [2,  8, 14],
     [3,  9, 15],
     [4, 10, 16],
     [5, 11, 17], 
     [6, 12, 18]]
)

In [31]:
print(x)

[[ 1  7 13]
 [ 2  8 14]
 [ 3  9 15]
 [ 4 10 16]
 [ 5 11 17]
 [ 6 12 18]]


What is the dimension of matrix x?

In [32]:
x.shape

(6, 3)

Select the 3rd column of the Array

In [33]:
x[:,2]

array([13, 14, 15, 16, 17, 18])

Select the 3rd row

In [34]:
x[2,:]

array([ 3,  9, 15])

Select all the elements up until element 2 of the array

In [35]:
x[:2]

array([[ 1,  7, 13],
       [ 2,  8, 14]])

Select all the elements starting from Index 2

In [36]:
x[2:]

array([[ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17],
       [ 6, 12, 18]])

##### Diagonal matrics

Create a diagonal matrix `m_diag`, in which the elements of the diagonal are the first 6 numbers of `v = np.arange(1,12)`.

Use the function `np.diag` ([Link to numpy documentation](https://numpy.org/doc/stable/reference/generated/numpy.diag.html)).

In [38]:
a = np.arange(1,12)[:6]

m_diag = np.diag(a)
m_diag



array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [39]:
a

array([1, 2, 3, 4, 5, 6])

In [40]:
m_diag.shape

(6, 6)